
/*

  Generated by Sony PSP Application AppWizard

  Version : 2.0.0

  File : main.c

  Description : main file for psp projet

*/

// CONFIG.C ET .H est OK (verifié, testé)
// RAM.C ET .H est OK (verifié, testé)
// IMAGE.C et .H OK (verifié, testé)
// VRAM.C et .H est OK (verifié, testé)
// IMAGEBMP <- A TERMINER MAIS OK POUR LA MEMOIRE (verifié, testé)
// LANGUAGE <- OK (verifié, testé)
// MENU.C ET .H corrigé (verifié, testé)
// FONT.C ET .H OK (verifié, testé)
// PSARDUMP.C ET .H OK (verifié, testé)
// FILE.C ET .H OK (verifié, testé)
// GRAPHIC.C ET .H OK normalement (verifié presque entierement, reste plus que les blit mais normalement c bon)
// IMAGEPNG <- OK MAIS fopen, fclose font perdre 384 octets !! ?

// VERIFIER LES STRUCTURES AVEC SCEIOREAD ET SIZEOF PARCE QU'ELLE SONT ALIGNEES ET CA PEUT FAUSSER LE CODE
// PROBLEME AVEC OPTIMISATION O2 (SCAN NE FONCTIONNE PAS CORRECTEMENT, LA LISTE DES FICHIERS RESTE TJS AU 1ER FICHIER)

// PROBLEME AVEC DISC0: N'AFFICHE PAS LE PARENT FOLDER


// *** INCLUDES ***

#include "Utils/file.h"
#include "Utils/config.h"
#include "Utils/psardump.h"
#include "Utils/menu.h"
#include "Utils/language.h"
#include <stdlib.h>
#include <psprtc.h>
#include <pspumd.h>
#include <pspusb.h>
#include <pspusbstor.h>

#include "Utils/ram.h"


// *** DEFINES ***

#define _printf					pspDebugScreenPrintf

#define MAIN_TITLE				"MPH FIRMWARE LAUNCHER"
#define MAIN_VERSION			"1.4.0"
#define MAIN_CONFIG_HEADER		";\r\n; MPH Firmware launcher configuration file\r\n;\r\n; Generated by MPH Firmware launcher %s\r\n;\r\n; Date : %d/%d/%d, %d:%d:%d\r\n;"

#define MAIN_FILE_CONFIG		"/mphfl.inf"
#define MAIN_FILE_FONT			"/res/font.png"
#define MAIN_FILE_BACKGROUND	"/res/back.png"
#define MAIN_FILE_LAUNCHER		"/mphfl.elf"

#define MAIN_FILTER_EBOOT		".pbp"

#define MAIN_FOLDER_FLASH0		"flash0"
#define MAIN_FOLDER_FLASH1		"flash1"

#define MAIN_KEYNAME_FIRMWARE	"FIRMWARE#"
#define MAIN_KEYNAME_DRIVER		"DRIVER"
#define	MAIN_KEYNAME_OPTION		"OPTION"

#define MAIN_VARNAME_INSTALL	"Install_Folder"
#define MAIN_VARNAME_FLASH0		"Flash0_Folder"
#define MAIN_VARNAME_FLASH1		"Flash1_Folder"
#define MAIN_VARNAME_VERSION	"Version"
#define	MAIN_VARNAME_DEBUGPRINT	"DebugPrint"
#define	MAIN_VARNAME_LANGUAGE	"Language"
#define	MAIN_VARNAME_LOGFILE	"LogFile"
#define	MAIN_VARNAME_OLDSYSTEM	"OldSystem"
#define	MAIN_VARNAME_DELETEPBP	"DeletePbp"
#define	MAIN_VARNAME_ENABLEUSB	"EnableUsb"

#define	MAIN_CHOOSE_FILE		0x0
#define MAIN_CHOOSE_FOLDER		0x1

#define MAIN_CHOOSE_DEVICE		0x1
#define	MAIN_CHOOSE_NEWFOLDER	0x2


// *** STRUCTURES ***

typedef u32 (*MAIN_CHOOSE_CALL) (void *);

typedef struct MainOption	// Main options
{
 char language[32];			// Name of language
 u32 debugPrint;			// If 1, print debug message
 u32 oldSystem;				// If 1, use old root system instead new driver system
 u32 logFile;				// If 1, create a log file
 u32 delPbp;				// If 1, delete PBP file after installation of a firmware
 u32 enableUsb;				// If 1, enable the USB in the menu
} MainOption;

typedef struct MainChooseOption
{
 char path[FILE_SIZE_PATH];	// Pointer to string which contains path
 char filter[16];			// Filter fo files
 u8 type;					// Type of choose (0 = file, 1 = folder)
 u8 flag;					// Options flag
 MAIN_CHOOSE_CALL func;		// Calling function
} MainChooseOption;


// *** GLOBALS VARIABLES ***

Menu *mainMenu;							// Menu
char mainPath[FILE_SIZE_PATH];			// Path of the program
ConfigFile mainConfig;					// Configuration file
MainOption mainOption;					// Options
char mainAuthor[32];					// Author of language for about menu
int mainLaunch = 0;						// Launch flag
int mainSaveConfig = 1;					// Save config flag

MainChooseOption *mainChooseOption;		// Pointer to option parameters for choose functions
char mainChoosePath[FILE_SIZE_PATH];	// Path used by choose functions
MainChooseOption mainCopySrc;			// Source parameters for choose functions
MainChooseOption mainCopyDest;			// Destination parameters for choose functions
char mainKeyname[16];					// Key name of current firmware choosed
char mainString[512];					// Temporary string to use


// *** MODULE INITIALISATION ***

PSP_MODULE_INFO("MPHFL_Main",0x1000,1,1);
PSP_MAIN_THREAD_ATTR(0x0);


// *** FUNCTIONS DECLARATIONS ***

u32 menuFunc_color (u32);

u32 menuFunc_main (void);

u32 menuFunc_launchMain (MenuItem *);
u32 menuFunc_config (MenuItem *);
u32 menuFunc_configSave (MenuItem *);
u32 menuFunc_about (MenuItem *);
u32 menuFunc_exit (MenuItem *);

u32 menuFunc_scan (MenuItem *);
u32 menuFunc_scanExec (MenuItem *);

u32 menuFunc_install (MenuItem *);
u32 menuFunc_installAutomatic (MenuOption *);
u32 menuFunc_installAutomaticExec (MenuItem *);
u32 menuFunc_installManual (MenuOption *);
u32 menuFunc_installManualExec (MenuItem *);

u32 menuFunc_launch (MenuSub *);

u32 menuFunc_copyMain (MenuSub *);
u32 menuFunc_copy (MenuSub *);
u32 menuFunc_copyExec (MenuItem *);

u32 menuFunc_check (MenuSub *);

u32 menuFunc_uninstall (MenuSub *);
u32 menuFunc_uninstallExec (MenuItem *);

u32 menuFunc_chooseMain (MenuSub *);
u32 menuFunc_choose (MenuSub *);
u32 menuFunc_chooseExit (MenuItem *);
u32 menuFunc_chooseExecFile (MenuOption *);
u32 menuFunc_chooseExecFolder (MenuItem *);
u32 menuFunc_chooseBrowse (MenuOption *);
u32 menuFunc_chooseDevice (MenuSub *);
u32 menuFunc_chooseNewFolder (MenuSub *);
int menuFunc_chooseNewFolderThread (SceSize, void *);

void mainExit (u32);
u32 waitButton (u32, u32);
char *findPath (const char *);
void debugPrint (char *);
u32 loadStartModule (char *, u32);


// *** FUNCTIONS CALLBACKS ***

int CallbackExit (int arg1, int arg2, void *common)
{
 // Exit without saving
 mainSaveConfig = 0;
 mainMenu->run = 0;

 return 0;
}

int CallbackThread (SceSize args, void *argp)
{
 int cbid;


 cbid = sceKernelCreateCallback("ExitCallback",CallbackExit,NULL);
 sceKernelRegisterExitCallback(cbid);

 sceKernelSleepThreadCB();

 return 0;
}

int SetupCallbacks (void)
{
 int thid;


 thid = sceKernelCreateThread("UpdateThread",CallbackThread,0x11,0xFA0,PSP_THREAD_ATTR_USER,0);
 if (thid >= 0) sceKernelStartThread(thid,0,0);

 return thid;
}

// *** MENUS FUNCTIONS ***

u32 menuFunc_color (u32 color)
{
 static GRAPHIC_COLOR_TYPE rr = 0xFF, rg =  0xFF, rb = 0xFF;
 static u32 ir = 1, ig = 1, ib = 1;
 GRAPHIC_COLOR_TYPE r,g,b;


 // Get the composante
 r = GRAPHIC_GET_COLOR_R(color);
 g = GRAPHIC_GET_COLOR_G(color);
 b = GRAPHIC_GET_COLOR_B(color);

 // Calculate new random color
 if ((r == rr) && (g == rg) && (b == rb))
 {
  rr = rand() % 0x100;
  rg = rand() % 0x100;
  rb = rand() % 0x100;
 }

 // Create new color
 ir = (r < rr) ? 1 : ((r > rr) ? -1 : 0);
 ig = (g < rg) ? 1 : ((g > rg) ? -1 : 0);
 ib = (b < rb) ? 1 : ((b > rb) ? -1 : 0);

 r += ir;
 g += ig;
 b += ib;

 // Create the color
 return GRAPHIC_MAKE_COLOR(r,g,b,0xFF);
}

u32 menuFunc_main (void)
{
 MenuBar *bar;


 // Refresh the usb mode
 if (mainOption.enableUsb)
  sceUsbActivate(0x1C8);
 else
  sceUsbDeactivate();

 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,MAIN_TITLE);

 // Create bar
 menuBarCreate(&bar,1,1);
 menuBarAttach(mainMenu,bar);

 // Create items
 menuBarAddItem(bar,NULL,languageGetString(25),1,menuFunc_launchMain);
 menuBarAddItem(bar,NULL,languageGetString(26),1,menuFunc_config);
 menuBarAddItem(bar,NULL,languageGetString(27),1,menuFunc_about);
 menuBarAddItem(bar,NULL,languageGetString(28),1,menuFunc_exit);

 // Initialize pointers
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_launchMain (MenuItem *item)
{
 MenuOption *option;
 ConfigVariable *var, *version;
 char keyname[16];
 int x;


 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(29));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create list options
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(30),1,menuFunc_scan);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(31),1,menuFunc_install);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(8),1,(MENU_ITEM_FUNC) menuFunc_main);

 // Get the firmware installed list
 for (x=0;;x++)
 {
  // Create the key name
  sprintf(keyname,"%s%d",MAIN_KEYNAME_FIRMWARE,x);

  // Find the variable
  if (configRead(&mainConfig,keyname,MAIN_VARNAME_INSTALL,&var)) break;

  // Add the firmware to list
  sprintf(mainString,"%s : %s (%s)",languageGetString(23),((configRead(&mainConfig,keyname,MAIN_VARNAME_VERSION,&version)) ? languageGetString(24) : (char *) version->value),(char *) var->value);
  menuListAddOption(mainMenu->list,&option,mainString,1,NULL);

  // Set the firmware number in user variable
  option->user = (void *) x;

  // Add the menu to firmware
  menuOptionAddSub(option,NULL,languageGetString(25),1,menuFunc_launch);
  menuOptionAddSub(option,NULL,languageGetString(32),1,menuFunc_copyMain);
  menuOptionAddSub(option,NULL,languageGetString(33),1,menuFunc_check);
  menuOptionAddSub(option,NULL,languageGetString(34),1,menuFunc_uninstall);
 }

 // For reinitialize choose option in child functions
 mainCopySrc.path[0] = 0;

 // Init pointers
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_config (MenuItem *item)
{
 MenuOption *option;
 MenuSub *sub;
 LanguageList listlang;
 int x;


 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(26));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create list options
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,menuFunc_configSave);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(7),1,(MENU_ITEM_FUNC) menuFunc_main);

 // Language
 menuListAddOption(mainMenu->list,&option,languageGetString(41),1,NULL);

 // Init first to keep option to good value
 menuInitPointer(mainMenu);

 memset(&listlang,0,sizeof(LanguageList));
 languageGetList(findPath(LANGUAGE_FOLDER_PATH),&listlang);

 // Add the default language
 menuOptionAddSub(option,&sub,LANGUAGE_DEFAULT_NAME,1,NULL);
 option->cur = sub;

 // Add other language
 for (x=0;x<listlang.count;x++)
 {
  if (strcasecmp(listlang.headers[x].name,LANGUAGE_DEFAULT_NAME))
  {
   menuOptionAddSub(option,&sub,listlang.headers[x].name,1,NULL);
   if (!(strcasecmp(sub->name,mainOption.language))) option->cur = sub;
  }
 }

 languageFreeList(&listlang);

 // Debug print
 menuListAddOption(mainMenu->list,&option,languageGetString(42),1,NULL);

 menuOptionAddSub(option,NULL,languageGetString(5),1,NULL);
 menuOptionAddSub(option,NULL,languageGetString(4),1,NULL);

 option->cur = (mainOption.debugPrint) ? option->subs->next : option->subs;

 // Old system
 menuListAddOption(mainMenu->list,&option,languageGetString(43),1,NULL);

 menuOptionAddSub(option,NULL,languageGetString(5),1,NULL);
 menuOptionAddSub(option,NULL,languageGetString(4),1,NULL);

 option->cur = (mainOption.oldSystem) ? option->subs->next : option->subs;

 // Log file
 menuListAddOption(mainMenu->list,&option,languageGetString(44),1,NULL);

 menuOptionAddSub(option,NULL,languageGetString(5),1,NULL);
 menuOptionAddSub(option,NULL,languageGetString(4),1,NULL);

 option->cur = (mainOption.logFile) ? option->subs->next : option->subs;

 // Delete pbp
 menuListAddOption(mainMenu->list,&option,languageGetString(45),1,NULL);

 menuOptionAddSub(option,NULL,languageGetString(5),1,NULL);
 menuOptionAddSub(option,NULL,languageGetString(4),1,NULL);

 option->cur = (mainOption.delPbp) ? option->subs->next : option->subs;

 // Enable usb
 menuListAddOption(mainMenu->list,&option,languageGetString(46),1,NULL);

 menuOptionAddSub(option,NULL,languageGetString(5),1,NULL);
 menuOptionAddSub(option,NULL,languageGetString(4),1,NULL);

 option->cur = (mainOption.enableUsb) ? option->subs->next : option->subs;

 return 0;
}

u32 menuFunc_configSave (MenuItem *item)
{
 MenuOption *option;
 LanguageList listlang;


 // Get first option
 option = mainMenu->list->options;

 // Language
 strncpy(mainOption.language,option->cur->name,32);
 mainOption.language[31] = 0;

 memset(&listlang,0,sizeof(LanguageList));
 languageGetList(findPath(LANGUAGE_FOLDER_PATH),&listlang);

 if (languageLoad(languageGetListFilename(&listlang,mainOption.language)))
 {
  strcpy(mainOption.language,LANGUAGE_DEFAULT_NAME);
  languageLoad(languageGetListFilename(&listlang,mainOption.language));
 }

 strcpy(mainAuthor,(languageGetListAuthor(&listlang,mainOption.language)) ? languageGetListAuthor(&listlang,mainOption.language) : languageGetString(24));

 languageFreeList(&listlang);

 // Debug print
 option = option->next;
 mainOption.debugPrint = (option->cur == option->subs) ? 0 : 1;

 // Old system
 option = option->next;
 mainOption.oldSystem = (option->cur == option->subs) ? 0 : 1;

 // Log file
 option = option->next;
 mainOption.logFile = (option->cur == option->subs) ? 0 : 1;

 // Delete pbp
 option = option->next;
 mainOption.delPbp = (option->cur == option->subs) ? 0 : 1;

 // Enable usb
 option = option->next;
 mainOption.enableUsb = (option->cur == option->subs) ? 0 : 1;

 // Call parent function for recreate it
 return menuFunc_main();
}

u32 menuFunc_about (MenuItem *item)
{
 u32 x;


 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(27));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create list informations
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(8),1,(MENU_ITEM_FUNC) menuFunc_main);

 sprintf(mainString,"%s : %s",languageGetString(23),MAIN_VERSION);

 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

 for (x=47;x<53;x++) menuListAddOption(mainMenu->list,NULL,languageGetString(x),2,NULL);

 sprintf(mainString,"%s : %s (%s : %s)",languageGetString(41),mainOption.language,languageGetString(53),mainAuthor);
 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

 // Init pointers
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_exit (MenuItem *item)
{
 // Exit menu
 mainMenu->run = 0;

 return 0;
}

u32 menuFunc_scan (MenuItem *item)
{
 ConfigVariable *var;


 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(30));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(4),1,menuFunc_scanExec);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(5),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 menuListAddOption(mainMenu->list,NULL,languageGetString(54),2,NULL);
 menuListAddOption(mainMenu->list,NULL,languageGetString(55),2,NULL);

 // Verify if old list exists
 sprintf(mainKeyname,"%s0",MAIN_KEYNAME_FIRMWARE);
 if (!(configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var))) menuListAddOption(mainMenu->list,NULL,languageGetString(56),2,NULL);

 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 menuListAddOption(mainMenu->list,NULL,languageGetString(57),2,NULL);

 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_scanExec (MenuItem *item)
{
 ConfigKey *key;
 ConfigVariable var;
 FileList filelist;
 char install[FILE_SIZE_PATH], version[16];
 u32 lost, modified;
 int x, keyid;


 // Add wait message in list
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 menuListAddOption(mainMenu->list,NULL,languageGetString(9),2,NULL);

 // Show the message
 menuDraw(mainMenu);

 // Delete old infos in list
 while (mainMenu->list->options) menuListDelOption(mainMenu->list,mainMenu->list->options);

 // Erase the old firmware list
 for (x=0;;x++)
 {
  // Create the key name
  sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,x);

  // Find the key
  key = configFindKey(&mainConfig,mainKeyname);
  if (!(key)) break; 

  // Erase key
  configDeleteKey(&mainConfig,key);
 }

 // Scan memory stick and create new list
 fileGetList(FILE_DEVICE_MS,PSAR_NAME_INSTALL,FILE_LIST_FILE | FILE_LIST_RECURSIVE,&filelist);

 var.type = CONFIG_TYPE_STRING;
 for (x=0,keyid=0;x<filelist.count;x++)
 {
  // Check the firmware
  if (!(psarCheckFirmware(filelist.list[x],install,version,NULL,&lost,&modified)))
  {
   // Check variables
   if (install[0])
   {
    // Add in list
	sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,keyid++);

	// Get the folder of install file
	strrchr(filelist.list[x],'/')[0] = 0;

	var.value = filelist.list[x];
	configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var);

	// Add version if exists
	if (version[0])
	{
	 var.value = version;
	 configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_VERSION,&var);
	}

	// Update list if errors
	if ((lost) || (modified))
	{
	 sprintf(mainString,"- %s : %s (%d %s, %d %s)",install,languageGetString(18),modified,languageGetString(21),lost,languageGetString(20));
	 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);
	}
   }
  }
 }

 // Free result
 fileFreeList(&filelist);

 // Update bar
 while (mainMenu->bar->items) menuBarDelItem(mainMenu->bar,mainMenu->bar->items);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 // Update list
 if (mainMenu->list->options) menuListAddOption(mainMenu->list,NULL,"",2,NULL);

 sprintf(mainString,"%d %s",x,languageGetString(58));
 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

 // Init pointers
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_install (MenuItem *item)
{
 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(31));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(8),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 menuListAddOption(mainMenu->list,NULL,languageGetString(59),2,NULL);
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 
 menuListAddOption(mainMenu->list,NULL,languageGetString(60),1,menuFunc_installAutomatic);
 menuListAddOption(mainMenu->list,NULL,languageGetString(61),1,menuFunc_installManual);

 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_installAutomatic (MenuOption *option)
{
 MenuItem *item;
 MenuOption *option2;
 MenuSub *sub;


 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(35));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,&item,languageGetString(62),1,menuFunc_installAutomaticExec);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(7),1,(MENU_ITEM_FUNC) menuFunc_install);

 // Test if already initialized
 if (!(mainCopySrc.path[0]))
 {
  // Initialize copy variables
  strcpy(mainCopySrc.path,FILE_DEVICE_MS);
  mainCopySrc.type = MAIN_CHOOSE_FILE;
  mainCopySrc.flag = MAIN_CHOOSE_DEVICE;
  strcpy(mainCopySrc.filter,MAIN_FILTER_EBOOT);
  mainCopySrc.func = (MAIN_CHOOSE_CALL) menuFunc_installAutomatic;

  strcpy(mainCopyDest.path,FILE_DEVICE_MS);
  mainCopyDest.type = MAIN_CHOOSE_FOLDER;
  mainCopyDest.flag = MAIN_CHOOSE_NEWFOLDER;
  mainCopyDest.func = (MAIN_CHOOSE_CALL) menuFunc_installAutomatic;
 }

 // Add PBP choose option
 menuListAddOption(mainMenu->list,&option2,languageGetString(63),1,NULL);
 menuOptionAddSub(option2,&sub,languageGetString(13),1,menuFunc_chooseMain);
 sub->user = (void *) &mainCopySrc;

 menuListAddOption(mainMenu->list,NULL,mainCopySrc.path,2,NULL);
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);

 // Add destination folder option
 menuListAddOption(mainMenu->list,&option2,languageGetString(77),1,NULL);
 menuOptionAddSub(option2,&sub,languageGetString(13),1,menuFunc_chooseMain);
 sub->user = (void *) &mainCopyDest;

 menuListAddOption(mainMenu->list,NULL,mainCopyDest.path,2,NULL);
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);

 // Add copy flash1 option
 menuListAddOption(mainMenu->list,&option2,languageGetString(32),1,NULL);

 menuOptionAddSub(option2,NULL,languageGetString(4),1,NULL);
 menuOptionAddSub(option2,NULL,languageGetString(5),1,NULL);

 // Save copy flash1 option pointer to a global variable
 item->user = (void *) option2;
 
 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_installAutomaticExec (MenuItem *item)
{
 MenuOption *option;
 ConfigVariable *var, var2;
 char version[16];
 u8 copyflash1;
 u32 result, x;


 // Get the copy flash1 choice
 copyflash1 = (((MenuOption *) item->user)->cur == ((MenuOption *) item->user)->subs) ? 1 : 0;

 // Add wait message in list
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 menuListAddOption(mainMenu->list,&option,languageGetString(9),2,NULL);

 // Show the message
 menuDraw(mainMenu);

 // Remove last '/' in path
 mainCopyDest.path[strlen(mainCopyDest.path) - 1] = 0;

 // Try to install firmware
 result = (psarInstallFirmware(mainCopySrc.path,mainCopyDest.path,MAIN_FOLDER_FLASH0,mainOption.delPbp)) ? 1 : 0;

 // If no error
 if (!(result))
 {
  // Find a free firmware key name
  for (x=0;;x++)
  {
   // Create the name
   sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,x);

   // Find the variable
   if (configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var)) break;
  }

  var2.type = CONFIG_TYPE_STRING;

  // Add install folder in configuration file
  var2.value = (void *) mainCopyDest.path;
  configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var2);

  // Add version in configuration file
  sprintf(mainString,"%s/%s",mainCopyDest.path,PSAR_NAME_INSTALL);
  psarCheckFirmware(mainString,NULL,version,NULL,NULL,NULL);

  var2.value = (void *) version;
  configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_VERSION,&var2);

  // If copy flash1 choosed
  if (copyflash1)
  {
   sprintf(mainString,"%s/%s",mainCopyDest.path,MAIN_FOLDER_FLASH1);
   result = (fileCopyFolder(FILE_DEVICE_FLASH1,mainString,NULL)) ? 2 : 0;

   // Add flash1 folder in configuration file
   if (!(result))
   {
    var2.value = (void *) mainString;
    configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_FLASH1,&var2);
   }
  }
 }

 // Update bar
 while (mainMenu->bar->items) menuBarDelItem(mainMenu->bar,mainMenu->bar->items);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 // Update list
 menuListDelOption(mainMenu->list,option);
 menuListAddOption(mainMenu->list,NULL,languageGetString((result != 1) ? 64 : 65),2,NULL);

 if (result == 2)
 {
  menuListAddOption(mainMenu->list,NULL,"",2,NULL);
  menuListAddOption(mainMenu->list,NULL,languageGetString(66),2,NULL);
 }

 // Init pointers
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_installManual (MenuOption *option)
{
 MenuItem *item;
 MenuOption *option2;
 MenuSub *sub;


 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(36));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,&item,languageGetString(62),1,menuFunc_installManualExec);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(7),1,(MENU_ITEM_FUNC) menuFunc_install);

 // Test if already initialized
 if (!(mainCopySrc.path[0]))
 {
  // Initialize copy variables
  strcpy(mainCopySrc.path,FILE_DEVICE_MS);
  mainCopySrc.type = MAIN_CHOOSE_FOLDER;
  mainCopySrc.flag = MAIN_CHOOSE_DEVICE;
  mainCopySrc.func = (MAIN_CHOOSE_CALL) menuFunc_installManual;

  strcpy(mainCopyDest.path,FILE_DEVICE_MS);
  mainCopyDest.type = MAIN_CHOOSE_FOLDER;
  mainCopyDest.flag = MAIN_CHOOSE_DEVICE;
  mainCopyDest.func = (MAIN_CHOOSE_CALL) menuFunc_installManual;
 }

 // Add flash0 folder choose option
 menuListAddOption(mainMenu->list,&option2,languageGetString(67),1,NULL);
 menuOptionAddSub(option2,&sub,languageGetString(13),1,menuFunc_chooseMain);
 sub->user = (void *) &mainCopySrc;

 menuListAddOption(mainMenu->list,NULL,mainCopySrc.path,2,NULL);
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);

 // Add flash1 folder choose option
 menuListAddOption(mainMenu->list,&option2,languageGetString(68),1,NULL);
 menuOptionAddSub(option2,&sub,languageGetString(13),1,menuFunc_chooseMain);
 sub->user = (void *) &mainCopyDest;

 menuListAddOption(mainMenu->list,NULL,mainCopyDest.path,2,NULL);
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 
 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_installManualExec (MenuItem *item)
{
 MenuOption *option;
 ConfigVariable *var, var2;
 char version[16];
 u32 result, x;


 // Add wait message in list
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 menuListAddOption(mainMenu->list,&option,languageGetString(9),2,NULL);

 // Show the message
 menuDraw(mainMenu);

 // Remove last '/' in path
 mainCopySrc.path[strlen(mainCopySrc.path) - 1] = 0;
 mainCopyDest.path[strlen(mainCopyDest.path) - 1] = 0;

 // Try to install firmware
 result = (psarCreateInstallFile(mainCopySrc.path,mainCopySrc.path)) ? 1 : 0;

 // If no error
 if (!(result))
 {
  // Find a free firmware key name
  for (x=0;;x++)
  {
   // Create the name
   sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,x);

   // Find the variable
   if (configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var)) break;
  }

  var2.type = CONFIG_TYPE_STRING;

  // Add install folder in configuration file
  var2.value = (void *) mainCopySrc.path;
  configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var2);

  // Add version in configuration file
  sprintf(mainString,"%s/%s",mainCopySrc.path,PSAR_NAME_INSTALL);
  psarCheckFirmware(mainString,NULL,version,NULL,NULL,NULL);

  var2.value = (void *) version;
  configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_VERSION,&var2);

  // Add flash1 folder in configuration file
  var2.value = (void *) mainCopyDest.path;
  configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_FLASH1,&var2);
 }

 // Update bar
 while (mainMenu->bar->items) menuBarDelItem(mainMenu->bar,mainMenu->bar->items);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 // Update list
 menuListDelOption(mainMenu->list,option);
 menuListAddOption(mainMenu->list,NULL,languageGetString((result) ? 65 : 64),2,NULL);

 // Init pointers
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_launch (MenuSub *sub)
{
 MenuOption *option;
 ConfigFile file;
 ConfigVariable *var, var2;
 char *temp;
 int error;


 // Get the key name with user variable of parent
 sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,((int) sub->parent->user));

 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 menuListAddOption(mainMenu->list,&option,languageGetString(9),2,NULL);

 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);

 // Show the wait message
 menuDraw(mainMenu);

 // Set current firmware to launch in configuration file
 configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var);
 sprintf(mainString,"%s/%s",(char *) var->value,PSAR_NAME_INSTALL);
 
 // Open install file
 file.opened = 0;
 configLoad(&file,mainString);

 var2.type = CONFIG_TYPE_STRING;

 // Copy flash0 variable
 error = 1;
 sprintf(mainString,"%s1",PSAR_KEYNAME_FOLDER);

 if (!(configRead(&file,mainString,PSAR_VARNAME_FOLDER,&var)))
 {
  if (var->type == CONFIG_TYPE_STRING)
  {
   temp = strchr((char *) var->value,'/');
   if (temp)
	temp = &temp[1];
   else
	temp = "";

   var2.value = (void *) temp;
   configWrite(&mainConfig,MAIN_KEYNAME_DRIVER,MAIN_VARNAME_FLASH0,&var2);

   // No error
   error = 0;
  }
 }

 if (!(error))
 {
  error = 2;

  // Copy flash1 variable
  if (!(configRead(&mainConfig,mainKeyname,MAIN_VARNAME_FLASH1,&var)))
  {
   if (var->type == CONFIG_TYPE_STRING)
   {
    temp = strchr((char *) var->value,'/');
    if (temp)
 	 temp = &temp[1];
    else
	 temp = "";

    var2.value = (void *) temp;
    configWrite(&mainConfig,MAIN_KEYNAME_DRIVER,MAIN_VARNAME_FLASH1,&var2);

	// No error
	error = 0;
   }
  }
 }

 // Close install file
 configClose(&file,0,NULL);

 // If error, quit with message error
 if (error)
 {
  // Update list
  menuListDelOption(mainMenu->list,option);
  menuListAddOption(mainMenu->list,NULL,(error == 1) ? languageGetString(12) : languageGetString(69),2,NULL);

  // Init pointers
  menuInitPointer(mainMenu);

  return 0;
 }

 // Set the launch flag
 mainLaunch = 1;

 // Call Exit func
 menuFunc_exit(NULL);

 return 0;
}

u32 menuFunc_copyMain (MenuSub *sub)
{
 // Get the key name with user variable
 sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,((int) sub->parent->user));

 return menuFunc_copy(sub);
}

u32 menuFunc_copy (MenuSub *sub)
{
 MenuOption *option;
 ConfigVariable *var, *version;
 MenuSub *sub2;


 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(32));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(70),1,menuFunc_copyExec);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(7),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 menuListAddOption(mainMenu->list,NULL,languageGetString(71),2,NULL);

 // Get the key name with user variable of parent
 configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var);

 sprintf(mainString,"%s : %s (%s)",languageGetString(23),((configRead(&mainConfig,mainKeyname,MAIN_VARNAME_VERSION,&version)) ? languageGetString(24) : (char *) version->value),(char *) var->value);
 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

 // Default destination is installation folder
 sprintf(mainString,"%s/",(const char *) var->value);

 // Try to get flash1 folder
 if (!(configRead(&mainConfig,mainKeyname,MAIN_VARNAME_FLASH1,&var)))
 {
  if (var->type == CONFIG_TYPE_STRING)
  {
   // Create folder if don't exists
   sceIoMkdir((const char *) var->value,0777);

   // Copy path
   sprintf(mainString,"%s/",(const char *) var->value);
  }
 }

 // Test if already initialized
 if (!(mainCopySrc.path[0]))
 {
  // Initialize copy variables
  strcpy(mainCopySrc.path,FILE_DEVICE_FLASH1);
  mainCopySrc.type = MAIN_CHOOSE_FOLDER;
  mainCopySrc.flag = MAIN_CHOOSE_DEVICE;
  mainCopySrc.func = (MAIN_CHOOSE_CALL) menuFunc_copy;

  strcpy(mainCopyDest.path,mainString);
  mainCopyDest.type = MAIN_CHOOSE_FOLDER;
  mainCopyDest.flag = MAIN_CHOOSE_NEWFOLDER;
  mainCopyDest.func = (MAIN_CHOOSE_CALL) menuFunc_copy;
 }

 // Add source option
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);

 menuListAddOption(mainMenu->list,&option,languageGetString(72),1,NULL);
 menuOptionAddSub(option,&sub2,languageGetString(13),1,menuFunc_chooseMain);
 sub2->user = (void *) &mainCopySrc;

 menuListAddOption(mainMenu->list,NULL,mainCopySrc.path,2,NULL);

 // Add dest option
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);

 menuListAddOption(mainMenu->list,&option,languageGetString(73),1,NULL);
 menuOptionAddSub(option,&sub2,languageGetString(13),1,menuFunc_chooseMain);
 sub2->user = (void *) &mainCopyDest;
 
 menuListAddOption(mainMenu->list,NULL,mainCopyDest.path,2,NULL);

 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_copyExec (MenuItem *item)
{
 MenuOption *option;
 ConfigVariable var;
 int result;


 // Remove last '/' in path
 mainCopySrc.path[strlen(mainCopySrc.path) - 1] = 0;
 mainCopyDest.path[strlen(mainCopyDest.path) - 1] = 0;

 // Add wait message in list
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 menuListAddOption(mainMenu->list,&option,languageGetString(9),2,NULL);

 // Show the message
 menuDraw(mainMenu);

 // Copy folders
 result = fileCopyFolder(mainCopySrc.path,mainCopyDest.path,NULL);

 // Copy path in configuration file if copy ok
 if (!(result))
 {
  // Write the value
  var.type = CONFIG_TYPE_STRING;
  var.value = (void *) mainCopyDest.path;

  configWrite(&mainConfig,mainKeyname,MAIN_VARNAME_FLASH1,&var);
 }

 // Update bar
 while (mainMenu->bar->items) menuBarDelItem(mainMenu->bar,mainMenu->bar->items);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 // Update list
 menuListDelOption(mainMenu->list,option);
 menuListAddOption(mainMenu->list,NULL,((result) ? languageGetString(74) : languageGetString(75)),2,NULL);

 // Init pointers
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_check (MenuSub *sub)
{
 MenuOption *option;
 ConfigVariable *var, *var2;
 char install[FILE_SIZE_PATH], version[16];
 u32 good, lost, modified;
 int x;


 // Get the key name with user variable of parent
 sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,((int) sub->parent->user));

 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(37));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,(MENU_ITEM_FUNC) menuFunc_launchMain);

 menuListAddOption(mainMenu->list,NULL,languageGetString(76),2,NULL);

 configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var);

 sprintf(mainString,"- %s : %s",languageGetString(23),((configRead(&mainConfig,mainKeyname,MAIN_VARNAME_VERSION,&var2)) ? languageGetString(24) : (char *) var2->value));
 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

 sprintf(mainString,"- %s : %s",languageGetString(77),(char *) var->value);
 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

 sprintf(mainString,"- %s : %s",languageGetString(78),languageGetString(22));
 if (!(configRead(&mainConfig,mainKeyname,MAIN_VARNAME_FLASH1,&var)))
 {
  if (var->type == CONFIG_TYPE_STRING) sprintf(mainString,"- %s : %s",languageGetString(78),(char *) var->value);
 }
 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 menuListAddOption(mainMenu->list,NULL,languageGetString(79),2,NULL);

 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);
 
 // Add wait message in list
 menuListAddOption(mainMenu->list,&option,languageGetString(9),2,NULL);

 // Show wait message
 menuDraw(mainMenu);

 // Check install file
 configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var);

 sprintf(mainString,"%s/%s",(char *) var->value,PSAR_NAME_INSTALL);
 x = psarCheckFirmware(mainString,install,version,&good,&lost,&modified);

 // Update list
 menuListDelOption(mainMenu->list,option);

 if (!(x))
 {
  sprintf(mainString,"- %s : %s",languageGetString(23),((version[0]) ? version : languageGetString(24)));
  menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

  sprintf(mainString,"- %s : %s",languageGetString(77),((install[0]) ? install : languageGetString(24)));
  menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);

  sprintf(mainString,"- %s (%s : %d, %s : %d, %s, %d)",languageGetString(18),languageGetString(19),good,languageGetString(20),lost,languageGetString(21),modified);
  menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);
 }
 else
  menuListAddOption(mainMenu->list,NULL,languageGetString(11),2,NULL);

 return 0;
}

u32 menuFunc_uninstall (MenuSub *sub)
{
 MenuItem *item;
 ConfigVariable *var, *version;
 u32 firmnum;


 // Get the key name with user variable of parent
 sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,(int) sub->parent->user);
 firmnum = (int) sub->parent->user;

 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString(38));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(5),1,(MENU_ITEM_FUNC) menuFunc_launchMain);
 menuBarAddItem(mainMenu->bar,&item,languageGetString(4),1,menuFunc_uninstallExec);

 // Save number of firmware
 item->user = (void *) firmnum;

 configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var);

 sprintf(mainString,"%s : %s (%s)",languageGetString(23),((configRead(&mainConfig,mainKeyname,MAIN_VARNAME_VERSION,&version)) ? languageGetString(24) : (char *) version->value),(char *) var->value);
 menuListAddOption(mainMenu->list,NULL,mainString,2,NULL);
 menuListAddOption(mainMenu->list,NULL,languageGetString(80),2,NULL);

 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_uninstallExec (MenuItem *item)
{
 MenuOption *option;
 ConfigKey *key;
 ConfigVariable *var;
 int result, x;


 // Add wait message in list
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);
 menuListAddOption(mainMenu->list,&option,languageGetString(9),2,NULL);

 // Show the message
 menuDraw(mainMenu);

 configRead(&mainConfig,mainKeyname,MAIN_VARNAME_INSTALL,&var);

 // Uninstall firmware
 sprintf(mainString,"%s/%s",(char *) var->value,PSAR_NAME_INSTALL);
 result = psarUninstallFirmware(mainString);

 // Erase firmware in configuration file if uninstalled
 if (!(result))
 {
  configDeleteKey(&mainConfig,configFindKey(&mainConfig,mainKeyname));

  // Reorder the firmware in configuration file
  for (x=((int) item->user)+1;;x++)
  {
   // Create the key name
   sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,x);

   // Find the key
   key = configFindKey(&mainConfig,mainKeyname);
   if (!(key)) break;

   // Create the new name
   sprintf(mainKeyname,"%s%d",MAIN_KEYNAME_FIRMWARE,x-1);

   // Rename the key
   strcpy(key->name,mainKeyname);
  }
 }

 // Update bar
 while (mainMenu->bar->items) menuBarDelItem(mainMenu->bar,mainMenu->bar->items);
 menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,(MENU_ITEM_FUNC) menuFunc_launchMain);
 
 // Update list
 menuListDelOption(mainMenu->list,option);
 menuListAddOption(mainMenu->list,NULL,((result) ? languageGetString(11) : languageGetString(81)),2,NULL);

 // Init pointers
 menuInitPointer(mainMenu);

 return 0;
}

u32 menuFunc_chooseMain (MenuSub *sub)
{
 // Get options
 mainChooseOption = (MainChooseOption *) sub->user;

 // Init current path
 strcpy(mainChoosePath,mainChooseOption->path);

 // Take the last folder
 strrchr(mainChoosePath,'/')[1] = 0;

 // Call menuFunc_choose
 return menuFunc_choose(NULL);
}

u32 menuFunc_choose (MenuSub *sub)
{
 MenuOption *option, *optiondev;
 MenuSub *sub2, *cur = NULL;
 FileList filelist;
 int x;


 // Delete old bar if exist
 menuBarDelete(mainMenu->bar);

 // Delete old list if exist
 menuListDelete(mainMenu->list);

 // Set title
 menuSetTitle(mainMenu,languageGetString((mainChooseOption->type == MAIN_CHOOSE_FOLDER) ? 39 : 40));

 // Create new bar
 menuBarCreate(&mainMenu->bar,1,1);
 menuBarAttach(mainMenu,mainMenu->bar);

 // Create new list
 menuListCreate(&mainMenu->list,1);
 menuListAttach(mainMenu,mainMenu->list);

 // Initialize menu

 // Get list
 if (fileGetList(mainChoosePath,mainChooseOption->filter,FILE_LIST_FOLDER | FILE_LIST_WITHPARENT | ((mainChooseOption->type == MAIN_CHOOSE_FILE) ? FILE_LIST_FILE : 0),&filelist))
 {
  strcpy(mainChoosePath,FILE_DEVICE_MS);
  fileGetList(mainChoosePath,mainChooseOption->filter,FILE_LIST_FOLDER | FILE_LIST_WITHPARENT | ((mainChooseOption->type == MAIN_CHOOSE_FILE) ? FILE_LIST_FILE : 0),&filelist);
 }

 // If folder, button ok to choose
 if (mainChooseOption->type == MAIN_CHOOSE_FOLDER) menuBarAddItem(mainMenu->bar,NULL,languageGetString(6),1,menuFunc_chooseExecFolder);

 menuBarAddItem(mainMenu->bar,NULL,languageGetString(7),1,menuFunc_chooseExit);

 // Show device option
 if (mainChooseOption->flag & MAIN_CHOOSE_DEVICE)
 {
  menuListAddOption(mainMenu->list,&optiondev,languageGetString(15),1,NULL);

  menuOptionAddSub(optiondev,&sub2,FILE_DEVICE_FLASH0,1,menuFunc_chooseDevice);
  sub2->user = (void *) sub;
  if (!(strncasecmp(sub2->name,mainChoosePath,strlen(sub2->name)))) cur = sub2;

  menuOptionAddSub(optiondev,&sub2,FILE_DEVICE_FLASH1,1,menuFunc_chooseDevice);
  sub2->user = (void *) sub;
  if (!(strncasecmp(sub2->name,mainChoosePath,strlen(sub2->name)))) cur = sub2;

  menuOptionAddSub(optiondev,&sub2,FILE_DEVICE_MS,1,menuFunc_chooseDevice);
  sub2->user = (void *) sub;
  if (!(strncasecmp(sub2->name,mainChoosePath,strlen(sub2->name)))) cur = sub2;

  // If UMD present
  if (sceUmdCheckMedium(0))
  {
   // Mount UMD to disc0: file system
   sceUmdActivate(1,FILE_DEVICE_UMD);

   // Wait for init
   sceUmdWaitDriveStat(UMD_WAITFORINIT);

   menuOptionAddSub(optiondev,&sub2,FILE_DEVICE_UMD,1,menuFunc_chooseDevice);
   sub2->user = (void *) sub;
   if (!(strncasecmp(sub2->name,mainChoosePath,strlen(sub2->name)))) cur = sub2;
  }
 }

 // Add current folder info
 sprintf(mainString,"%s :",languageGetString(14));
 menuListAddOption(mainMenu->list,&option,mainString,1,NULL);

 // Add create folder option
 if (mainChooseOption->flag & MAIN_CHOOSE_NEWFOLDER)
  menuOptionAddSub(option,NULL,languageGetString(16),1,menuFunc_chooseNewFolder);
 else
  option->used = 2;

 menuListAddOption(mainMenu->list,NULL,mainChoosePath,2,NULL);
 menuListAddOption(mainMenu->list,NULL,"",2,NULL);

 // Create sub list
 for (x=0;x<filelist.count;x++)
 {
  // Check if folder or file
  if (filelist.list[x][strlen(filelist.list[x]) - 1] == '/')
  {
   // Eliminate last '/'
   filelist.list[x][strlen(filelist.list[x]) - 1] = 0;

   // Copy name of child folder
   sprintf(mainString,"%s/",&strrchr(filelist.list[x],'/')[1]);

   // Add as option
   menuListAddOption(mainMenu->list,&option,mainString,1,menuFunc_chooseBrowse);
  }
  else
  {
   // Copy name of file
   sprintf(mainString,"%s",&strrchr(filelist.list[x],'/')[1]);

   // Add as option
   menuListAddOption(mainMenu->list,&option,mainString,1,menuFunc_chooseExecFile);
  }

  option->user = (void *) sub;
 }

 // Free list
 fileFreeList(&filelist);

 // Init pointers
 menuSetFocus(mainMenu,MENU_FOCUS_BAR);
 menuInitPointer(mainMenu);

 // Init current device
 if (mainChooseOption->flag & MAIN_CHOOSE_DEVICE) optiondev->cur = cur;

 return 0;
}

u32 menuFunc_chooseExit (MenuItem *item)
{
 mainChooseOption->func(NULL);

 return 0;
}

u32 menuFunc_chooseExecFile (MenuOption *option)
{
 // Copy string
 strcpy(mainChooseOption->path,mainChoosePath);
 strcat(mainChooseOption->path,option->name);

 // Exit choose functions
 menuFunc_chooseExit(NULL);

 return 0;
}

u32 menuFunc_chooseExecFolder (MenuItem *item)
{
 // Copy string
 strcpy(mainChooseOption->path,mainChoosePath);

 // Exit choose functions
 menuFunc_chooseExit(NULL);

 return 0;
}

u32 menuFunc_chooseBrowse (MenuOption *option)
{
 // Copy name in user
 if (!(strcmp(option->name,"../")))
 {
  // Get parent folder
  strrchr(mainChoosePath,'/')[0] = 0;
  strrchr(mainChoosePath,'/')[1] = 0;
 }
 else
  // Get child folder
  strcat(mainChoosePath,option->name);
 
 // Recreate the choose menu
 menuFunc_choose(NULL);

 return 0;
}

u32 menuFunc_chooseDevice (MenuSub *sub)
{
 // Copy name of sub as new path
 strcpy(mainChoosePath,sub->name);

 // Recreate the menu choose
 menuFunc_choose(NULL);

 return 0;
}

u32 menuFunc_chooseNewFolder (MenuSub *sub)
{
 u32 argp;
 static char *folder;
 int thid;


 // Init variables
 folder = NULL;
 argp = (u32) &folder;

 // Create a thread for call OSK because he don't work in KERNEL mode
 thid = sceKernelCreateThread("OskThread",menuFunc_chooseNewFolderThread,0x11,0xFA0,PSP_THREAD_ATTR_USER,0);
 if (thid >= 0)
 {
  sceKernelStartThread(thid,sizeof(argp),&argp);
  sceKernelWaitThreadEnd(thid,NULL);
 }

 // If name given, create the folder
 if (folder)
 {
  if (folder[0])
  {
   // Create the full name
   sprintf(mainString,"%s%s",mainChoosePath,folder);

   // Create the folder
   sceIoMkdir(mainString,0777);

   // Go to the new folder
   sprintf(mainChoosePath,"%s/",mainString);

   // Recreate the choose menu
   menuFunc_choose(NULL);
  }
 }

 return 0;
}

int menuFunc_chooseNewFolderThread (SceSize args, void *argp)
{
 // Remove read only protection else OSK don't show messages !
 sceIoUnassign("flash1:");
 sceIoAssign("flash1:","lflash0:0,1","flashfat1:",IOASSIGN_RDWR,NULL,0);

 // Get folder name
 *((char **) *((u32 *) argp)) = menuGetOskText(mainMenu,languageGetString(17),languageGetString(16),languageGetOskId(),16);

 // Protect flash1
 sceIoUnassign("flash1:");
 sceIoAssign("flash1:","lflash0:0,1","flashfat1:",IOASSIGN_RDONLY,NULL,0);

 // Exit and delete thread
 sceKernelExitDeleteThread(0);

 return 0;
}

// *** FUNCTIONS ***

void mainExit (u32 save)
{
 pspTime time;
 ConfigVariable value;
 struct SceKernelLoadExecParam param;


 // Get the date / time
 sceRtcGetCurrentClockLocalTime(&time);

 // Create header
 sprintf(mainString,MAIN_CONFIG_HEADER,MAIN_VERSION,time.year,time.month,time.day,time.hour,time.minutes,time.seconds);

 // Write options
 value.type = CONFIG_TYPE_INTEGER;

 value.value = &mainOption.debugPrint;
 configWrite(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_DEBUGPRINT,&value);

 value.value = &mainOption.logFile;
 configWrite(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_LOGFILE,&value);

 value.value = &mainOption.oldSystem;
 configWrite(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_OLDSYSTEM,&value);

 value.value = &mainOption.delPbp;
 configWrite(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_DELETEPBP,&value);

 value.value = &mainOption.enableUsb;
 configWrite(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_ENABLEUSB,&value);

 value.type = CONFIG_TYPE_STRING;

 value.value = mainOption.language;
 configWrite(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_LANGUAGE,&value);
 
 // Save and close configuration file
 configClose(&mainConfig,save,mainString);

 // Free all VRAM (if forget to free memory)
// vramFreeAll();

 // Free language
 languageFree();

 // Cleanup usb
 sceUsbDeactivate();
 sceUsbStop(PSP_USBSTOR_DRIVERNAME,0,0);
 sceUsbStop(PSP_USBBUS_DRIVERNAME,0,0);

 // Call firmware launcher if needed
 if (mainLaunch)
 {
  // Path arg
  param.size = sizeof(param);
  param.argp = (void *) mainPath;
  param.args = strlen(mainPath) + 1;
  param.key = NULL;

  // Launch the program
  sceKernelLoadExec(findPath(MAIN_FILE_LAUNCHER),&param);
 }

 // Exit
 sceKernelExitGame();
}

u32 waitButton (u32 codemask, u32 block)
{
 SceCtrlData pad;
 static u32 oldButtons = 0;
 

 for (;;)
 {
  // Read the buttons
  sceCtrlReadBufferPositive(&pad,1);

  // Check the buttons
  if ((oldButtons != pad.Buttons) || (!(block)))
  {
   // Save the buttons
   oldButtons = pad.Buttons;

   // Exit if ok
   if (pad.Buttons & codemask) return pad.Buttons;
  }

  // For wait without block
  sceDisplayWaitVblankStart();
 }
}

char *findPath (const char *name)
{
 static char string[FILE_SIZE_PATH];


 // Copy main path
 strcpy(string,mainPath);

 // Copy name
 strcat(string,name);

 return string;
}

void debugPrint (char *string)
{
 if (mainOption.debugPrint)
 {
  _printf("%s\n",string);
//  waitButton(PSP_CTRL_CROSS,0);
 }
}

u32 loadStartModule (char *path, u32 start)
{
 u32 loadResult, startResult;
 int status;


 loadResult = sceKernelLoadModule(path,0,NULL);
 if (loadResult & 0x80000000) return 1;

 if (start)
 {
  startResult = sceKernelStartModule(loadResult,0,NULL,&status,NULL);
  if (loadResult != startResult) return 2;
 }

 return 0;
}

int main (int argc, char *argv[])
{
 ConfigVariable *var;
 FontType font;
 LanguageList listlang;


 // Init display and HOME button
 pspDebugScreenInit();
 pspDebugScreenClear();
 SetupCallbacks();

 // Setup Pad
 sceCtrlSetSamplingCycle(0);
 sceCtrlSetSamplingMode(0);

 // Init system entries before graphics functions else crashes !?
 psarInitSysEntries();

/*
 // Show the available ram before enter the program
 _printf("Free ram before : %d\n",ramAvailable());
*/

 // Protect flash0 and flash1
 sceIoUnassign("flash0:");
 sceIoAssign("flash0:","lflash0:0,0","flashfat0:",IOASSIGN_RDONLY,NULL,0);

 sceIoUnassign("flash1:");
 sceIoAssign("flash1:","lflash0:0,1","flashfat1:",IOASSIGN_RDONLY,NULL,0);

 // Init USB
 loadStartModule("flash0:/kd/semawm.prx",1);
 loadStartModule("flash0:/kd/usbstor.prx",1);
 loadStartModule("flash0:/kd/usbstormgr.prx",1);
 loadStartModule("flash0:/kd/usbstorms.prx",1);
 loadStartModule("flash0:/kd/usbstorboot.prx",1);

 sceUsbStart(PSP_USBBUS_DRIVERNAME,0,0);
 sceUsbStart(PSP_USBSTOR_DRIVERNAME,0,0);
 sceUsbstorBootSetCapacity(0x800000);
 sceUsbDeactivate();

 // Find the path of program
 strcpy(mainPath,argv[0]);
 strrchr(mainPath,'/')[0] = 0;

 // Init options with default value
 memset(&mainOption,0,sizeof(MainOption));

 // Load configuration file
 mainConfig.opened = 0;

 if (!(configLoad(&mainConfig,findPath(MAIN_FILE_CONFIG))))
 {
  // Read options
  if (!(configRead(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_DEBUGPRINT,&var))) mainOption.debugPrint = (*((u32 *) var->value)) ? 1 : 0;
  if (!(configRead(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_LANGUAGE,&var))) strncpy(mainOption.language,var->value,32);
  mainOption.language[31] = 0;
  if (!(configRead(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_LOGFILE,&var))) mainOption.logFile = (*((u32 *) var->value)) ? 1 : 0;
  if (!(configRead(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_OLDSYSTEM,&var))) mainOption.oldSystem = (*((u32 *) var->value)) ? 1 : 0;
  if (!(configRead(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_DELETEPBP,&var))) mainOption.delPbp = (*((u32 *) var->value)) ? 1 : 0;
  if (!(configRead(&mainConfig,MAIN_KEYNAME_OPTION,MAIN_VARNAME_ENABLEUSB,&var))) mainOption.enableUsb = (*((u32 *) var->value)) ? 1 : 0;
 }
 else
  configCreate(&mainConfig,findPath(MAIN_FILE_CONFIG));

 // Load language
 memset(&listlang,0,sizeof(LanguageList));
 languageGetList(findPath(LANGUAGE_FOLDER_PATH),&listlang);

 if (languageLoad(languageGetListFilename(&listlang,mainOption.language)))
 {
  strcpy(mainOption.language,LANGUAGE_DEFAULT_NAME);
  languageLoad(languageGetListFilename(&listlang,mainOption.language));
 }

 strcpy(mainAuthor,(languageGetListAuthor(&listlang,mainOption.language)) ? languageGetListAuthor(&listlang,mainOption.language) : languageGetString(24));

 languageFreeList(&listlang);

 debugPrint(languageGetString(0));

 // Init graphic
 graphicInit();
 
 // Init random value
 srand(clock());

 // Init font
 font.begin = 32;
 font.end = 150;
 font.carrow = 10;
 font.width = 16;
 font.height = 16;
 font.incx = 17;
 font.incy = 16;
 font.border = 0;

 debugPrint(languageGetString(1));

 if (menuInit(findPath(MAIN_FILE_FONT),&font))
 {
  graphicTerm();
  debugPrint(languageGetString(2));
  exit(0);

  return -1;
 }

 debugPrint(languageGetString(3));

 // Init main menu
 menuCreate(&mainMenu,MAIN_TITLE,GRAPHIC_MAKE_COLOR(0x0,0x0,0x0,0xFF),findPath(MAIN_FILE_BACKGROUND),160,PSP_CTRL_CROSS,1,menuFunc_color,1);

 // Create menu
 menuFunc_main();

 // Manage main menu
 menuManage(mainMenu);

 // Delete menus
 menuDelete(mainMenu);

 // Terminate menu functions
 menuTerm();

 // Terminate graphic
 graphicTerm();

 // Exit with saving
 mainExit(mainSaveConfig);

/*
 // Show the available ram after exit the program
 pspDebugScreenInit();
 pspDebugScreenClear();

 _printf("Free ram after : %d\n",ramAvailable());
 waitButton(PSP_CTRL_CROSS,1);
*/

 return 0;
}
