
#ifndef LANGUAGE_DEFAULT_INCLUDED
#define LANGUAGE_DEFAULT_INCLUDED

/*

  Default language resource

  By MPH (mphtheone@hotmail.com)

*/


#define	LANGUAGE_DEFAULT_SIZE		82

char *LANGUAGE_DEFAULT_TEXT[LANGUAGE_DEFAULT_SIZE] =
{
// Debug messages

 "Initialize graphic ...",
 "Initialize menu font ...",
 "Menu font initializing failed, exit ...",
 "Create menus ...",


// Menu messages

// Shared (4)

 "YES",
 "NO",
 "OK",
 "CANCEL",
 "RETURN TO MENU",
 "PLEASE WAIT ...",
 "WARNING",
 "ERROR, NO INSTALL FILE FOUND !",
 "ERROR ON LOADING INSTALL FILE !",
 "CHOOSE",
 "CURRENT FOLDER",
 "DEVICE",
 "NEW FOLDER",
 "FOLDER NAME",
 "FILES",
 "GOOD",
 "LOST",
 "MODIFIED",
 "NONE",
 "VERSION",
 "UNKNOW",


// Titles (25)

 "LAUNCH",
 "CONFIGURATION",
 "ABOUT",
 "EXIT",

 "FIRMWARE LIST",
 "SCAN",
 "INSTALL A FIRMWARE",
 "COPY FLASH1",
 "CHECK",
 "UNINSTALL",

 "AUTOMATIC INSTALLATION",
 "MANUAL INSTALLATION",

 "CHECK FIRMWARE",
 "UNINSTALL FIRMWARE",

 "CHOOSE FOLDER",
 "CHOOSE FILE",


// Configuration menu (41)

 "LANGUAGE",
 "PRINT DEBUG",
 "USE OLD SYSTEM",
 "SAVE LOG FILE",
 "DELETE PBP FILE AFTER INSTALLATION",
 "ENABLE USB IN MENU",


// About menu (47)

 "CREATED BY MPH",
 "PSAR DECRYPTION IS PERFORMED BY PSPPET",
 "GRAPHIC FUNCTIONS BASED ON PSPSDK SAMPLES",
 "OSK FUNCTIONS BASED ON MCZONK SAMPLE",
 "THANKS TO PSPPET AND PS2DEV TEAM",
 "AND ALL PSP COMMUNITY ;-)",
 "AUTHOR",


// Scan menu (54)

 "THIS MENU WILL FOUND INSTALLED FIRMWARE ON THE MS",
 "THIS MAYBE TAKE A TIME",
 "THE OLD FIRMWARE LIST WILL BE ERASED",
 "DO YOU BEGIN THE SCAN ?",
 "FIRMWARE(S) FOUND",


// Install menu (59)

 "CHOOSE YOUR TYPE OF INSTALLATION :",
 "AUTOMATICALLY (WITH AN EBOOT.PBP)",
 "MANUALLY (WITH A FLASH0 FOLDER)",
 "INSTALL",
 "PBP FILE :",
 "THE FIRMWARE HAS BEEN SUCCESFULLY INSTALLED",
 "ERROR ON FIRMWARE INSTALLATION",
 "ERROR ON FLASH1 COPY",
 "FLASH0 FOLDER :",
 "FLASH1 FOLDER :",


// Launch menu (69)

 "ERROR, NO FLASH1 FOLDER DEFINED !",


// Copy flash1 menu (70)

 "COPY",
 "COPY FLASH1 FOR THE FIRMWARE :",
 "SOURCE FLASH1 FOLDER :",
 "DESTINATION FLASH1 FOLDER :",
 "COPY FAILED",
 "COPY SUCCESSFUL",


// Check menu (76)

 "INFORMATIONS IN CONFIGURATION FILE :",
 "INSTALL FOLDER",
 "FLASH1 FOLDER",
 "INFORMATIONS FOUND IN FIRMWARE :",


// Uninstall menu (80)

 "DO YOU REALLY UNINSTALL THIS FIRMWARE ?",
 "THE FIRMWARE HAS BEEN SUCCESFULLY UNINSTALLED"
};

#endif
